### ISSUE TITLE
how to deal with “Checkpoint file name"?i don't known how to run the code.Waiting for your answer!Thank you!

### ISSUE THREAD

**Issue by xcg1125** [THUwangcy/DeepTransRec#1]

**Comment by THUwangcy** [comment]
If you just want to run the code, leave this flag as default (""). 
The model will save its parameter every 50 epochs to a folder called "checkpoints", which is created automatically parallel to "src". Then if you want to continue training from a specific checkpoint, you can pass the name of checkpoint (in {timestamp}_{epoch} format) to this flag.

**Comment by xcg1125** [comment]
Thank you for your answer，i have run the code in your guide。Thank you very much！
