### ISSUE TITLE
I want to check your code for "Next Item Recommendation with Self-Attention". Could you please share in what format data is expected to be input

### ISSUE THREAD

**Issue by devaroundu** [THUwangcy/DeepTransRec#2]

**Comment by THUwangcy** [comment]
Each row is a record in following format (space separated):
\<user\> \<item\> \<rating\> \<timestamp\>

- \<user\> and \<item\> can be string or something else (but with no space). They will be reassigned ids.
- \<rating\> is not used, just cater to some datasets' original format. You can leave this column all ones.
- \<timestamp\> is in Unix timestamp format.

More information can be found in ***corpus.py***

**Comment by devaroundu** [comment]
Thanks a lot for your response !
I am planning to first use Amazon Dataset and try to reproduce the results as mentioned in the Paper.

Thank You.
Best Regards
